### ISSUE TITLE
Is it normal for data loading to take a long time during some training steps

### ISSUE THREAD

**Issue by icech** [guoqincode/Open-AnimateAnyone#101]
Every few training steps, there is a delay of several tens of seconds in data loading. Is it due to my CPU's performance？

**Comment by guoqincode** [comment]
Yes, dataloading is cpu intensive.

**Comment by icech** [comment]
> Yes, dataloading is cpu intensive.

thanks for you reply.  sorry to bother you,  have you encoutered this promblem? Could you please tell me the model of CPU you have used?   i have checked my cpu, all of them are Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz.
```
load_data_time: 0.0001, train_step_time: 0.665. 
load_data_time: 0.0001, train_step_time: 0.652
load_data_time: 0.0001, train_step_time: 0.640
load_data_time: 19.6173, train_step_time: 0.686 
load_data_time: 0.0002, train_step_time: 0.664
load_data_time: 0.0002, train_step_time: 0.639             
```
