### ISSUE TITLE
About stage 1 training（out of memory）

### ISSUE THREAD

**Issue by Mumuwei** [guoqincode/Open-AnimateAnyone#102]
Thanks for the good work. I had the following problem during training phase 1. I used four 40G A100s. As requested, I set the size of the image to 256 and left the rest of the Settings unchanged. The following error occurred. Thanks.

![1431705460400_ pic](https://github.com/guoqincode/Open-AnimateAnyone/assets/44329935/01eb91ef-e480-4b09-892c-91ce30db159a)
![1441705460418_ pic](https://github.com/guoqincode/Open-AnimateAnyone/assets/44329935/1b78203a-367f-4008-a030-7ef94924db8c)
![1451705460457_ pic](https://github.com/guoqincode/Open-AnimateAnyone/assets/44329935/3ba661d6-d0bc-470b-9165-b108e1f67ba3)

**Comment by guoqincode** [comment]
I tried 40G VRAM with res=256 and bs=2.

**Comment by Mumuwei** [comment]
Unfortunately I tried to change bs to 2, still out of video memory.
![image](https://github.com/guoqincode/Open-AnimateAnyone/assets/44329935/edb60f90-923f-43ee-81a7-aa3db6e8e0b1)

**Comment by Mumuwei** [comment]
I looked at the dataset.py and found that in stage1 , only the image of UBC dataset was read instead of the sequence. If bs was set to 2, then the input was only 2x3x256x256, why would it still out of memory?

**Comment by Mumuwei** [comment]
Sorry, it's just another multithreaded program preempting memory, not code related.

**Comment by ZhiyingDu** [comment]
> Sorry, it's just another multithreaded program preempting memory, not code related.

hi,bro,how do you solve this problem?
