### ISSUE TITLE
Problem with training with H100

### ISSUE THREAD

**Issue by Valentino-unova** [guoqincode/Open-AnimateAnyone#114]
Hi! I got this incompatibility problem with PyTorch when training with H100:

NVIDIA H100 PCIe with CUDA capability
sm_90 is not compatible with the current PyTorch installation.
The current PyTorch
install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.

<img width="1079" alt="Screenshot 2024-02-12 at 18 03 43" src="https://github.com/guoqincode/Open-AnimateAnyone/assets/155984641/79d20dcd-c3c0-49fe-9e16-7f62f2dd50f5">

The training is not started properly. Do you have any idea which PyTorch version in this case would fit with H100 while making the training work? Thanks a lot!

**Comment by guoqincode** [comment]
If you are using an H100, I recommend Torch 2.x
