### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by Valentino-L** [guoqincode/Open-AnimateAnyone#117]
Hi! I have encountered this invalid data error during training, it seems to be happening to all the videos but I processed all videos according to prepare_ubc.py. Do you have any idea what could've gone wrong? Thanks a lot!

<img width="551" alt="Screenshot 2024-02-20 at 00 30 41" src="https://github.com/guoqincode/Open-AnimateAnyone/assets/67510831/068345b2-6ab6-45ac-98ca-5945abec2da2">

**Comment by guoqincode** [comment]
Sorry, I have not encountered this problem. Are all your files mp4 format videos?
