### ISSUE TITLE
Stage 1 Results

### ISSUE THREAD

**Issue by hanweikung** [guoqincode/Open-AnimateAnyone#65]
I ran stage 1 training with a sample size of 256, a batch size of 4, and 60,000 training steps. However, the result seems wrong. What might be the issue?

![grid](https://github.com/guoqincode/AnimateAnyone-unofficial/assets/643825/0b775df9-ac38-434f-a904-e09154b7e7d1)

**Comment by sizhky** [comment]
how long did it take to train?

**Comment by garychan22** [comment]
@hanweikung have you ever figured out the reason?

**Comment by hanweikung** [comment]
> @hanweikung have you ever figured out the reason?

Unfortunately no, I'm unable to generate the desired results with this repository.

**Comment by MuhammadHammadBashir** [comment]
Hi @hanweikung I am also facing exact same situation as you did,  I trained with same configuration as your but getting same poor result,
what you suggest?

**Comment by hanweikung** [comment]
> Hi @hanweikung I am also facing exact same situation as you did, I trained with same configuration as your but getting same poor result, what you suggest?

Hi @MuhammadHammadBashir Unfortunately, I can't offer suggestions as I stopped using this repository after trying to troubleshoot it several times without success.
