### ISSUE TITLE
Some configuration doubts in motion_unet/config.json

### ISSUE THREAD

**Issue by chlinfeng1997** [guoqincode/Open-AnimateAnyone#85]
After we complete the training of Stage 1 and Stage 2, we try to use demo/animate.py to infer. When loading unet weights, we encounter the problem of missing some weights:
![1704774323955](https://github.com/guoqincode/Open-AnimateAnyone/assets/81463455/49b411b4-affd-43c7-86e5-18de88ed09d9)
We think the problem is that the UNet3DConditionModel should be used in config.json instead of UNet2DConditionModel. 
We would like to ask you how to fix it

**Comment by zhangtao22** [comment]
what's the solution?
