### ISSUE TITLE
Is CLIP image encoder really helpful?

### ISSUE THREAD

**Issue by kaleidoscopical** [guoqincode/Open-AnimateAnyone#97]
Nice work! I wonder whether including CLIP image encoder can really expedite the entire training process as claimed in the paper. Do you have any insight about it? Many thanks.

btw, I see `clip-vit-base-patch32` is used instead of `clip-vit-large-patch14` in the config file. Is there any consideration behind it?

**Comment by guoqincode** [comment]
I think CLIP embedding is probably just to maintain the CFG...

**Comment by guoqincode** [comment]
The dimensions of sd and clip-vit-base-patch32 are aligned.

**Comment by kaleidoscopical** [comment]
Thanks! Really helpful advices!

**Comment by garychan22** [comment]
@guoqincode hi, I got normal result when removing the clip feature, but weird result when including the clip feature. any reason?
